#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

CYCLES="${CYCLES:-6}"            # number of cycles to run
START="${START:-1}"               # start cycle number
SLEEP="${SLEEP:-0}"               # optional sleep between cycles
PLAN="${PLAN:-plan.md}"        # your plan markdown (relative to WORKDIR unless absolute)
WORKDIR="${WORKDIR:-.}"
CODEX_BIN="${CODEX_BIN:-codex}"
SKIP_EXISTING="${SKIP_EXISTING:-1}" # skip cycles with existing reports when set to 1

mkdir -p "$WORKDIR"
WORKDIR="$(cd "$WORKDIR" && pwd -P)"
cd "$WORKDIR"

resolve_path() {
  local path="$1"
  if [[ "$path" = /* ]]; then
    printf '%s\n' "$path"
  else
    printf '%s/%s\n' "$WORKDIR" "$path"
  fi
}

PLAN_PATH="$(resolve_path "$PLAN")"
DATA_LAKE_PATH="$(resolve_path "${DATA_LAKE:-data_lake}")"
CODE_LAKE_PATH="$(resolve_path "${CODE_LAKE:-code_lake}")"

if ! command -v "$CODEX_BIN" >/dev/null 2>&1; then
  echo "Missing '$CODEX_BIN' on PATH. Set CODEX_BIN to your Codex CLI executable."
  exit 1
fi

if ! [[ "$CYCLES" =~ ^[0-9]+$ ]]; then
  echo "CYCLES must be a non-negative integer."
  exit 1
fi
if ! [[ "$START" =~ ^[0-9]+$ ]] || (( START < 1 )); then
  echo "START must be an integer >= 1."
  exit 1
fi
if (( CYCLES == 0 )); then
  echo "CYCLES=0; nothing to do."
  exit 0
fi

[[ -f "$PLAN_PATH" ]] || { echo "Missing plan: $PLAN_PATH"; exit 1; }
[[ -d "$DATA_LAKE_PATH" ]] || echo "Warning: missing data lake directory: $DATA_LAKE_PATH"
[[ -d "$CODE_LAKE_PATH" ]] || echo "Warning: missing code lake directory: $CODE_LAKE_PATH"

REPORTS_DIR="$WORKDIR/reports"
mkdir -p "$REPORTS_DIR"
INDEX="$REPORTS_DIR/INDEX.md"
touch "$INDEX"

END=$((START + CYCLES - 1))

for ((i=START; i<=END; i++)); do
  c=$(printf "%02d" "$i")
  REPORT_FILE="$REPORTS_DIR/cycle_${c}.md"

  if [[ "$SKIP_EXISTING" == "1" && -f "$REPORT_FILE" ]]; then
    echo "Skipping cycle $c (report exists: $REPORT_FILE)"
    [[ "$SLEEP" == "0" ]] || sleep "$SLEEP"
    continue
  fi

  PROMPT="$(cat <<EOF
You are an autonomous research agent improving a research plan. You have full permission to run shell commands, read/edit files, and use the internet to download related public files if needed.

WORKDIR:
- $WORKDIR

LOCAL RESOURCES:
- Plan file: $PLAN_PATH
- Data lake: $DATA_LAKE_PATH
- Code lake: $CODE_LAKE_PATH
- Reports dir: $REPORTS_DIR
- Current cycle report path: $REPORT_FILE
- Memory index: $INDEX

KEY TOOLING RULE:
- Use Codex (you) for: research planning, experiment design, writing, integrating findings, project management, web research, and verification.
- Use Claude Code ONLY for coding-heavy research data processing (parsers, preprocessing pipelines, dataset builders, benchmarks, scripts).
  If you need Claude, start it from terminal with: bash -lc 'claude'
  Ask Claude to implement code + run it + write brief notes. You (Codex) must then verify with at least one command yourself.

OBJECTIVE (Cycle $c):
- Produce a deep, non-duplicative discovery cycle that materially improves $PLAN_PATH.
- Write the full report to: $REPORT_FILE
- Append 1 line of compact memory to: $INDEX (no duplicates).

INTERNET / EXTERNAL ARTIFACT POLICY:
- You have internet access. Use it whenever local files are insufficient.
- Create this directory if missing: mkdir -p "$DATA_LAKE_PATH/externals"
- Every EVEN cycle (i.e., cycle number divisible by 2), you MUST do a web-backed investigation AND save at least ONE external artifact into:
  $DATA_LAKE_PATH/externals/
  Examples: an .md with curated paper/dataset links + notes, a .bib file, a benchmark table .csv, a dataset metadata .json, a cloned repo README snapshot, or a small downloaded file.
- If you download anything, record: (a) URL, (b) where saved locally.

EXTERNAL DOWNLOAD GUARDRAILS:
- Prefer small artifacts (<20MB). Prefer metadata summaries (md/json/csv) over huge raw datasets.
- Always create/update: $DATA_LAKE_PATH/externals/README.md describing what you saved and why.

NON-NEGOTIABLE “PROOF-OF-WORK” REQUIREMENT (must satisfy at least TWO):
You must actually do at least TWO items and include evidence:
1) Run 1–5 shell commands to inspect local data/code and include commands + key output snippets.
2) Create/update a runnable code artifact in $CODE_LAKE_PATH and run a smoke test.
3) Produce a derived summary artifact in $DATA_LAKE_PATH generated by a command.
4) Web-backed investigation: save at least ONE external artifact into $DATA_LAKE_PATH/externals/ and cite it.
5) Literature micro-brief: 3–7 concrete papers/tools/datasets WITH LINKS and 2–3 sentences each on plan impact.
If you cannot complete any of the above, explain why and still leave behind a minimal artifact (stub script + TODO + acceptance checks).

REPORT LENGTH REQUIREMENT:
- Target 800–1500 words.
- Include at least 6 Findings bullets and at least 2 Plan improvements.
- If implementation-heavy, include a short “Design rationale” paragraph.

PROCEDURE (DO THIS EXACTLY):
1) Read $PLAN_PATH.
2) Read $INDEX and skim prior reports in $REPORTS_DIR to avoid duplicates.
3) Choose ONE theme and go deep by executing, not brainstorming:
   - Define 1–2 falsifiable hypotheses/decisions to settle this cycle.
   - Choose an investigation method (commands / code / data summarization / web-backed artifact / literature).
   - Produce artifacts and evidence per proof-of-work requirements.
4) If implementation becomes substantial, delegate to Claude.
5) Write the report with strict structure below, then update $INDEX.

THEME OPTIONS (pick exactly ONE):
A) Research/design deepening (hypotheses, metrics, ablations, baselines, risks) + proof-of-work items.
B) Implementation deepening: create/improve artifacts in $CODE_LAKE_PATH and/or derived outputs in $DATA_LAKE_PATH (Claude allowed, not required).

REPORT FORMAT (STRICT):
# Cycle $c: <short title>

## Theme + decision
- Theme (A or B):
- Decision / hypothesis to settle this cycle:

## Novelty check
- Not repeating (quote 2–4 bullets from $INDEX you avoided):
  - ...
- What is new in this cycle (1–2 sentences):

## Proof-of-work (required)
- Commands run (with 1–5 line outputs):
  - \`...\`
    - output: ...
- External artifacts saved (if any):
  - Path:
  - URL:
- Files created/modified (paths + what changed):
  - ...

## Findings (>=6, non-duplicative, backed by evidence)
- ...

## Plan improvements (>=2, specific edits to apply)
- Specify exact sections/headings in $PLAN_PATH to add/change (quote headings).
- Provide concrete inserts/edits.

## Concrete next experiments (1–2)
- Experiment:
  - Minimal setup:
  - Metrics:
  - Baselines/Ablations:
  - Expected outcomes:
  - Failure interpretation:

## If code was added/changed (only if applicable)
- What was implemented (Codex/Claude):
- How to run (exact commands):
- Where outputs go:
- Smoke test you ran:
- Design rationale (brief):

## References / links
- ...

FINAL ACTIONS (REQUIRED):
- Write the report to: $REPORT_FILE
- Append to $INDEX exactly one line:
  - cycle_$c: <1–2 lines summarizing NEW unique takeaways; must not duplicate prior index entries>

Now execute this cycle end-to-end and write $REPORT_FILE, then update $INDEX.
EOF
)"

  printf '%s' "$PROMPT" | "$CODEX_BIN" exec --skip-git-repo-check -

  [[ "$SLEEP" == "0" ]] || sleep "$SLEEP"
done

echo "Done: wrote $CYCLES reports under $REPORTS_DIR and updated $INDEX."

### Add below to the prompt if needed:
# CLAUDE BUDGET POLICY (STRICT):
# - Max ONE Claude session per cycle. (Max TWO only if the first output fails a smoke test and you cannot fix quickly.)
# - Claude is for implementation, not brainstorming.
# - ONE-SHOT: before calling Claude, prepare a single complete request (goal, file paths, inputs/outputs, acceptance checks). Ask Claude to implement end-to-end + run smoke test + summarize.
# - After Claude returns, do NOT call Claude again unless the smoke test fails.